### ISSUE TITLE
Main Menu: Campaign Selector

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/p2ce-panorama-ui#35]
### Which component should be improved?

UI/UX

### Describe your suggestion

The global menu should allow the player to pick which campaign menu they want to see.

- [x] Implement basic features of panel, 3 entries by default (P2:CE, Portal 2, Workshop)
- [ ] Dynamically add and remove campaign entries
- [x] Clicking an entry opens the respective menu
- [x] Saves the currently open menu when closing and relaunching the game
- [x] Do not let the player open this menu on the pause screen
- [ ] Search bar

### Expected result

The campaign selector panel works, and all the entries in this issue are accounted for.

**Comment by JJL772** [comment]
Scrapped

**Comment by Maxkatsur** [comment]
Which alternative for this issue?

**Comment by craftablescience** [comment]
No replacement. We went a different direction design-wise.
